setwd("./")
csv_list<-list.files(pattern = "*.csv")

data1 <- read.csv(csv_list[1])
data2 <- read.csv(csv_list[2])
data3 <- read.csv(csv_list[3])
data4 <- read.csv(csv_list[4])
data5 <- read.csv(csv_list[5])
data6 <- read.csv(csv_list[6])
data7 <- read.csv(csv_list[7])

plot(data1,type="l",ylim=c(30,100),col = 1,xlab="TIME(ms)",ylab="DISTAN(mm)")
par(new = TRUE)
plot(data2,type="l",ylim=c(30,100),col = 2,xlab="",ylab="")
par(new = TRUE)
plot(data3,type="l",ylim=c(30,100),col = 3,xlab="",ylab="")
par(new = TRUE)
plot(data3,type="l",ylim=c(30,100),col = 7,xlab="",ylab="")
par(new = TRUE)
plot(data5,type="l",ylim=c(30,100),col = 4,xlab="",ylab="")
par(new = TRUE)
plot(data6,type="l",ylim=c(30,100),col = 5,xlab="",ylab="")
par(new = TRUE)
plot(data7,type="l",ylim=c(30,100),col = 6,xlab="",ylab="")
